"""
Pytest configuration and fixtures for Generator service tests.
"""
import pytest
import os
from pathlib import Path
import sys


# Ensure repo root is on sys.path so `shared` imports work when running tests from this folder.
REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


# Set test environment variables
os.environ["OLLAMA_URL"] = "http://test-ollama:11434"
os.environ["OLLAMA_MODEL"] = "test-model"
os.environ["REQUIREMENTS_SERVICE_URL"] = "http://test-requirements:8000"
os.environ["TESTCASES_SERVICE_URL"] = "http://test-testcases:8000"
os.environ["AUTOMATIONS_SERVICE_URL"] = "http://test-automations:8000"
os.environ["PLAYWRIGHT_MCP_URL"] = "http://test-playwright:3000"
os.environ["GIT_SERVICE_URL"] = "http://test-git:8000"
os.environ["TESTS_REPO_URL"] = "https://github.com/test-org/test-repo.git"
os.environ["TESTS_REPO_BRANCH"] = "main"
os.environ["TEST_FILES_PATH"] = "tests/generated"


@pytest.fixture(scope="session")
def test_environment():
    """Provide test environment configuration."""
    return {
        "ollama_url": os.getenv("OLLAMA_URL"),
        "git_service_url": os.getenv("GIT_SERVICE_URL"),
        "tests_repo_url": os.getenv("TESTS_REPO_URL"),
    }


@pytest.fixture
def sample_test_case():
    """Provide a sample test case for testing."""
    return {
        "id": "test123abc",
        "title": "User Login Flow",
        "metadata": {
            "description": "Test user login with valid credentials",
            "preconditions": "User account exists in the system",
            "steps": [
                {
                    "action": "Navigate to login page",
                    "expected_result": "Login page is displayed"
                },
                {
                    "action": "Enter username and password",
                    "expected_result": "Credentials are accepted"
                },
                {
                    "action": "Click login button",
                    "expected_result": "User is redirected to dashboard"
                }
            ]
        }
    }


@pytest.fixture
def sample_automation():
    """Provide a sample automation script for testing."""
    return {
        "id": "auto123",
        "test_case_id": "test123abc",
        "title": "User Login Flow",
        "framework": "playwright",
        "script": """await page.goto('https://example.com/login');
await page.fill('input[name="username"]', 'testuser');
await page.fill('input[name="password"]', 'password123');
await page.click('button[type="submit"]');
await expect(page).toHaveURL(/.*dashboard/);""",
        "status": "not_started",
        "notes": "Generated by test"
    }


@pytest.fixture
def sample_git_result():
    """Provide a sample git push result for testing."""
    return {
        "success": True,
        "pr_url": "https://github.com/org/repo/pull/42",
        "pr_number": 42,
        "branch_name": "feat/test-test123-1702340567",
        "file_path": "tests/generated/user-login-flow-test123.spec.js",
        "repo_name": "test-repo",
        "cloned": True
    }


@pytest.fixture
def playwright_test_content():
    """Provide sample Playwright test file content."""
    return """// Auto-generated test by AI Test Platform
// Test ID: test123abc
// Generated: 2024-12-15T10:30:00Z

import { test, expect } from '@playwright/test';

test.describe('User Login Flow', () => {
  test('should execute User Login Flow', async ({ page }) => {
    await page.goto('https://example.com/login');
    await page.fill('input[name="username"]', 'testuser');
    await page.fill('input[name="password"]', 'password123');
    await page.click('button[type="submit"]');
    await expect(page).toHaveURL(/.*dashboard/);
  });
});
"""
